[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor = "8u2absR3zLEnTcsM542zjMNbeNzf1dpViq9FKPxAiFfd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build cp target/deploy/anchor.so /tests/fixtures"
